### ISSUE TITLE
Setup Bower

### ISSUE THREAD

**Issue by dghalbr** [dghalbr/tradeBinder#16]
Setup Bower on the app so that it controls our libraries and we can get them out of the repository.

**Comment by th3ALPHAnerd** [comment]
I'm almost finished with this; however, someone forgot to fix a merge conflict in index.html and accidentally pushed the auto generated diff.

**Comment by dghalbr** [comment]
Thanks. Is that going to dev or the branch you're working on?

**Comment by dghalbr** [comment]
I just made a pull request adding Jasmine Testing to the dev branch. When it gets merged it will have some bower stuff. You may want to look and see if it clashes with anything you are doing.

**Comment by neighbor983** [comment]
Check out BakerBranch i have bower.json, that holds a list of external lib, the .bowerrc file tells the files to be placed in the public/assets/libs all you have to do now is just enter the below command in your terminal.
$ bower install

If you want to add more libs just enter the below command to make sure bower.json is updated
$ bower install <PACKAGE> --save

**Comment by dghalbr** [comment]
Completed. Closing this issue.
