### ISSUE TITLE
Account: Register

### ISSUE THREAD

**Issue by dghalbr** [dghalbr/tradeBinder#17]
Get the Register page actually writing to mongodb.

**Comment by th3ALPHAnerd** [comment]
I'm working on getting this setup. Still doing a bit of research, but I think I should have something working by the weekend.

**Comment by th3ALPHAnerd** [comment]
I got the basic structure stubbed out. Code is checked out in the [feature/register branch](/dghalbr/tradeBinder/tree/feature/register).
