### ISSUE TITLE
Implement $locationProvider

### ISSUE THREAD

**Issue by dghalbr** [dghalbr/tradeBinder#21]
When running the node server, to access the application, the home link doesn't work. I guess it is because the route in server.js looks at "/" and AngularJS adds that "#" to the url. 

`app.get('/', function (req, res) {
    res.sendFile('index.html');
});`

$locationProvider can get rid of that "#" that gets added. I have only researched this a bit and it looked pretty straight forward. May have to set html5Mode to true as we

**Comment by neighbor983** [comment]
Have a look at BakerBranch.  There is no longer a # in the url.

**Comment by dghalbr** [comment]
Cool. I need you to explain this to me because there is no difference in how I implemented this but mine doesn't work lol.

**Comment by neighbor983** [comment]
It works when i run it through netbeans it works, but when I run it on node server is not working. I am going to have to do some reading.

**Comment by dghalbr** [comment]
Yeah I was trying through node too. It probably has something to do with how it serves up the files.

**Comment by dghalbr** [comment]
Update: I am working on this and it looks like its trying to bounce each path off of node instead of just handling it in Angular. Which looks to me like it wants us to declare every path in the node server.js file. Which is not ideal.

**Comment by dghalbr** [comment]
Ok, so I got this working on both Node and NetBeans. For some reason it doesn't want to load certain pages unless you click on Home first. I think we need to load up all of the HTML initially somehow?

**Comment by neighbor983** [comment]
BakerBranch now has templateCache. this will let you got back to the page once you have seen it without having to go to home. Not a solution but still saving a few request. when you run the below gulp command everything is handled for you.

$ gulp scripts

 or

$gulp

**Comment by dghalbr** [comment]
I have just implemented this without using gulp. I think gulp is great for templateCache and minify/concat, but am I right in thinking it would be best to do that prior to release for better performance instead of for functionality in development? @th3ALPHAnerd could you chime in on this one? Kent's implementation is an impressive one and works well, but it would require us to use gulp while we are making changes in real time. I was thinking we could use gulp as part of our pre-deployment steps to obfuscate and concatenate for performance prior to release? I have a pull request with my implementation and Kent's is in his BakerBranch.
