### ISSUE TITLE
bycrpt problem on npm start

### ISSUE THREAD

**Issue by neighbor983** [dghalbr/tradeBinder#30]
\
> bcrypt@0.8.5 install /home/pettymt/NetBeansProjects/tradeBinder/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/home/pettymt/NetBeansProjects/tradeBinder/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: Command not found
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: Leaving directory `/home/pettymt/NetBeansProjects/tradeBinder/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pettymt/Applications/node-v4.2.6-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "/home/pettymt/Applications/node-v4.2.6-linux-x64/bin/node" "/home/pettymt/Applications/node-v4.2.6-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pettymt/NetBeansProjects/tradeBinder/node_modules/bcrypt
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/home/pettymt/Applications/node-v4.2.6-linux-x64/bin/node" "/home/pettymt/Applications/node-v4.2.6-linux-x64/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pettymt/NetBeansProjects/tradeBinder/npm-debug.log

**Comment by th3ALPHAnerd** [comment]
Looks like you don't have make installed on your local machine. It should be located under the build-essential package. Here is the command on Ubuntu:

$ sudo apt-get install build-essential
