### ISSUE TITLE
CORS issue on Chrome

### ISSUE THREAD

**Issue by neighbor983** [dghalbr/tradeBinder#32]
Stacktrace when you try to do a search:
XMLHttpRequest cannot load https://api.deckbrew.com/mtg/cards?name=Black%20Lotus. Response for preflight has invalid HTTP status code 404

**Comment by th3ALPHAnerd** [comment]
We are now adding the JWT to the authorization header on every request to handle auth on our app. This is probably getting put into the the preflight request and causing it to blow up.

This raises a point that I haven't though about, but we are probably going to have to configure all our microservices to accept CORS requests. Blah.

**Comment by th3ALPHAnerd** [comment]
Just looked at the request, and yep:

access-control-request-headers:accept, authorization

I imagine if you remove the authorization header it should probably work.

**Comment by th3ALPHAnerd** [comment]
Created a pull request with the fix. Pull request link:

https://github.com/dghalbr/tradeBinder/pull/33

Basically, turned auth off for that request.
