### ISSUE TITLE
Logout on refresh

### ISSUE THREAD

**Issue by th3ALPHAnerd** [dghalbr/tradeBinder#37]
Whenever you refresh the page it logs you out of the app. This may be working as intended, but it seems like a odd behavior to me.

**Comment by neighbor983** [comment]
https://github.com/auth0/auth0-angular

describes a way to keep users logged in after a page refresh.

**Comment by th3ALPHAnerd** [comment]
This is a little different than what we are dealing with. That article is describing how to save a access token after being redirected to some SSO provider like google or facebook. Our issue is that we are calling the `UserService.logout` function on every initial app load. Rather, we should bind that function to an attribute on the main controller and call it whenever a user clicks on the logout button.
